// Run 24 sTGC geometry, SEEDED FROM THE RUN 22 FINAL ITERATION.
//
// beginTime 2023-12-10 00:00:00 is Gene's Run-24 "ideal" date (database_timestamp.txt),
// which is before the Run 24 ZF data (event time 2024-06-22), so this entry wins over
// Daniel's 20221220 identity placeholder. Version 000000 = initial Run-24 entry.
//
// The values are a verbatim copy of the Run 22 final constants, NOT a Run 24
// measurement. sTGC was removed and reinstalled between Run 22 and Run 24 on the same
// rails, so the expectation is mm-level movement, not cm. Starting Run 24 from these
// means the measured residual IS the Run22 -> Run24 movement, read directly, and it
// also keeps the Run 24 pickup measurement on an aligned geometry so it is comparable
// with Run 22 rather than being depressed by a nominal-geometry mismatch.
//
// Replace with a real Run 24 measurement once the first iteration is done; bump the
// time field to 000001 for that.
// Generated by script/stgcTableAddDelta.py:  StarDb/Geometry/stgc/pentOnStation.20211112.000002.C + deltas from /tmp/claude-2546/-direct-star-u-akio-fcstrk11-star-sw-fwd/999e4fd5-b5d9-4cdc-bbed-3d4d48f7c08f/scratchpad/deltas.txt
// new = previous + delta, delta = -(measured residual). Absolute
// regeneration is WRONG once StFttDb runs in DB mode -- see the guard in
// script/stgcQuadOffsets.C.
// pentOnStation, iteration 2 at 20211112 00:00:02.
// x/y are unchanged from .000001. What is new is t2, the PER-QUADRANT z.
//
// StgmGeo1.xml gives one z per station -- #707 used quadrant A's survey value for
// the whole plane -- while StFttDb keeps all four (idealPlaneZLocations_Quad*).
// Each pentagon is placed separately in AGML, so the difference belongs here:
//     t2 = StFttDb z(quad,station) - quadrant A z(station)
// Quadrant A is therefore 0 by construction. Largest term 2.9 mm (station 3, C).
// REQUIRES the float-zplane geometry (fe8ca6da33). t2 is measured against the
// un-truncated nominal 312.342/329.953/347.637/365.422; against a geometry built
// before that fix the nominal is 312.8385/330.8385/346.8385/364.8385 and these
// values are wrong by the truncation. This entry and that XML change are a matched
// pair -- a misalign table is only meaningful relative to the nominal it was
// measured against.
// per-quadrant offsets from FST->sTGC residuals. row = 4*station + k, k: 0=A 1=D 2=C 3=B (measured from the geometry, script/pentMap.C). correction = -(residual - global)
TDataSet *CreateTable() {
    if (!TClass::GetClass("St_Survey")) return 0;
Survey_st row;
St_Survey *tableSet = new St_Survey("pentOnStation",16);

    memset(&row,0,tableSet->GetRowSize());
        row.Id   = 1;
        row.r00  = 1.0;
        row.r01  = 0.0;
        row.r02  = 0.0;
        row.r10  = 0.0;
        row.r11  = 1.0;
        row.r12  = 0.0;
        row.r20  = 0.0;
        row.r21  = 0.0;
        row.r22  = 1.0;
        row.t0   = 2.09845;
        row.t1   = 4.60535;
        row.t2   = 0.00000;
    memcpy(&row.comment,"Station=1(Disk=0),Pent=1(Quad=A,x>0,y>0) geo(+0.809,+3.634) + align(+1.331,+1.794)\x00",1);
    tableSet->AddAt(&row);

    memset(&row,0,tableSet->GetRowSize());
        row.Id   = 2;
        row.r00  = 1.0;
        row.r01  = 0.0;
        row.r02  = 0.0;
        row.r10  = 0.0;
        row.r11  = 1.0;
        row.r12  = 0.0;
        row.r20  = 0.0;
        row.r21  = 0.0;
        row.r22  = 1.0;
        row.t0   = -1.13103;
        row.t1   = 4.55228;
        row.t2   = -0.24400;
    memcpy(&row.comment,"Station=1(Disk=0),Pent=2(Quad=D,x<0,y>0) geo(-0.369,+3.670) + align(-1.266,+1.911)\x00",1);
    tableSet->AddAt(&row);

    memset(&row,0,tableSet->GetRowSize());
        row.Id   = 3;
        row.r00  = 1.0;
        row.r01  = 0.0;
        row.r02  = 0.0;
        row.r10  = 0.0;
        row.r11  = 1.0;
        row.r12  = 0.0;
        row.r20  = 0.0;
        row.r21  = 0.0;
        row.r22  = 1.0;
        row.t0   = -4.92208;
        row.t1   = 0.15412;
        row.t2   = -0.02500;
    memcpy(&row.comment,"Station=1(Disk=0),Pent=3(Quad=C,x<0,y<0) geo(-4.251,+2.460) + align(-1.138,-1.960)\x00",1);
    tableSet->AddAt(&row);

    memset(&row,0,tableSet->GetRowSize());
        row.Id   = 4;
        row.r00  = 1.0;
        row.r01  = 0.0;
        row.r02  = 0.0;
        row.r10  = 0.0;
        row.r11  = 1.0;
        row.r12  = 0.0;
        row.r20  = 0.0;
        row.r21  = 0.0;
        row.r22  = 1.0;
        row.t0   = 5.91625;
        row.t1   = 0.52601;
        row.t2   = -0.17700;
    memcpy(&row.comment,"Station=1(Disk=0),Pent=4(Quad=B,x>0,y<0) geo(+4.774,+2.524) + align(+1.397,-1.685)\x00",1);
    tableSet->AddAt(&row);

    memset(&row,0,tableSet->GetRowSize());
        row.Id   = 5;
        row.r00  = 1.0;
        row.r01  = 0.0;
        row.r02  = 0.0;
        row.r10  = 0.0;
        row.r11  = 1.0;
        row.r12  = 0.0;
        row.r20  = 0.0;
        row.r21  = 0.0;
        row.r22  = 1.0;
        row.t0   = 0.83400;
        row.t1   = 3.53300;
        row.t2   = 0.00000;
    memcpy(&row.comment,"Station=2(Disk=1),Pent=1(Quad=A,x>0,y>0) geo(+0.834,+3.533) ; NO V HITS - geometry term only\x00",1);
    tableSet->AddAt(&row);

    memset(&row,0,tableSet->GetRowSize());
        row.Id   = 6;
        row.r00  = 1.0;
        row.r01  = 0.0;
        row.r02  = 0.0;
        row.r10  = 0.0;
        row.r11  = 1.0;
        row.r12  = 0.0;
        row.r20  = 0.0;
        row.r21  = 0.0;
        row.r22  = 1.0;
        row.t0   = -1.17713;
        row.t1   = 3.98837;
        row.t2   = -0.22200;
    memcpy(&row.comment,"Station=2(Disk=1),Pent=2(Quad=D,x<0,y>0) geo(-0.496,+3.540) + align(-1.205,+1.765)\x00",1);
    tableSet->AddAt(&row);

    memset(&row,0,tableSet->GetRowSize());
        row.Id   = 7;
        row.r00  = 1.0;
        row.r01  = 0.0;
        row.r02  = 0.0;
        row.r10  = 0.0;
        row.r11  = 1.0;
        row.r12  = 0.0;
        row.r20  = 0.0;
        row.r21  = 0.0;
        row.r22  = 1.0;
        row.t0   = -4.99263;
        row.t1   = 0.19277;
        row.t2   = -0.23000;
    memcpy(&row.comment,"Station=2(Disk=1),Pent=3(Quad=C,x<0,y<0) geo(-4.322,+2.442) + align(-1.046,-1.903)\x00",1);
    tableSet->AddAt(&row);

    memset(&row,0,tableSet->GetRowSize());
        row.Id   = 8;
        row.r00  = 1.0;
        row.r01  = 0.0;
        row.r02  = 0.0;
        row.r10  = 0.0;
        row.r11  = 1.0;
        row.r12  = 0.0;
        row.r20  = 0.0;
        row.r21  = 0.0;
        row.r22  = 1.0;
        row.t0   = 6.05033;
        row.t1   = 0.47379;
        row.t2   = 0.14100;
    memcpy(&row.comment,"Station=2(Disk=1),Pent=4(Quad=B,x>0,y<0) geo(+4.714,+2.437) + align(+1.539,-1.666)\x00",1);
    tableSet->AddAt(&row);

    memset(&row,0,tableSet->GetRowSize());
        row.Id   = 9;
        row.r00  = 1.0;
        row.r01  = 0.0;
        row.r02  = 0.0;
        row.r10  = 0.0;
        row.r11  = 1.0;
        row.r12  = 0.0;
        row.r20  = 0.0;
        row.r21  = 0.0;
        row.r22  = 1.0;
        row.t0   = 1.75587;
        row.t1   = 4.60284;
        row.t2   = 0.00000;
    memcpy(&row.comment,"Station=3(Disk=2),Pent=1(Quad=A,x>0,y>0) geo(+0.662,+3.703) + align(+1.139,+1.795)\x00",1);
    tableSet->AddAt(&row);

    memset(&row,0,tableSet->GetRowSize());
        row.Id   = 10;
        row.r00  = 1.0;
        row.r01  = 0.0;
        row.r02  = 0.0;
        row.r10  = 0.0;
        row.r11  = 1.0;
        row.r12  = 0.0;
        row.r20  = 0.0;
        row.r21  = 0.0;
        row.r22  = 1.0;
        row.t0   = -1.11224;
        row.t1   = 4.13515;
        row.t2   = -0.19300;
    memcpy(&row.comment,"Station=3(Disk=2),Pent=2(Quad=D,x<0,y>0) geo(-0.436,+3.655) + align(-1.193,+1.312)\x00",1);
    tableSet->AddAt(&row);

    memset(&row,0,tableSet->GetRowSize());
        row.Id   = 11;
        row.r00  = 1.0;
        row.r01  = 0.0;
        row.r02  = 0.0;
        row.r10  = 0.0;
        row.r11  = 1.0;
        row.r12  = 0.0;
        row.r20  = 0.0;
        row.r21  = 0.0;
        row.r22  = 1.0;
        row.t0   = -5.86228;
        row.t1   = 0.39389;
        row.t2   = -0.29100;
    memcpy(&row.comment,"Station=3(Disk=2),Pent=3(Quad=C,x<0,y<0) geo(-4.487,+2.537) + align(-1.375,-1.785)\x00",1);
    tableSet->AddAt(&row);

    memset(&row,0,tableSet->GetRowSize());
        row.Id   = 12;
        row.r00  = 1.0;
        row.r01  = 0.0;
        row.r02  = 0.0;
        row.r10  = 0.0;
        row.r11  = 1.0;
        row.r12  = 0.0;
        row.r20  = 0.0;
        row.r21  = 0.0;
        row.r22  = 1.0;
        row.t0   = 6.04068;
        row.t1   = 0.62434;
        row.t2   = -0.09400;
    memcpy(&row.comment,"Station=3(Disk=2),Pent=4(Quad=B,x>0,y<0) geo(+4.830,+2.461) + align(+1.482,-1.481)\x00",1);
    tableSet->AddAt(&row);

    memset(&row,0,tableSet->GetRowSize());
        row.Id   = 13;
        row.r00  = 1.0;
        row.r01  = 0.0;
        row.r02  = 0.0;
        row.r10  = 0.0;
        row.r11  = 1.0;
        row.r12  = 0.0;
        row.r20  = 0.0;
        row.r21  = 0.0;
        row.r22  = 1.0;
        row.t0   = 1.74485;
        row.t1   = 4.53699;
        row.t2   = 0.00000;
    memcpy(&row.comment,"Station=4(Disk=3),Pent=1(Quad=A,x>0,y>0) geo(+0.754,+3.601) + align(+1.079,+1.846)\x00",1);
    tableSet->AddAt(&row);

    memset(&row,0,tableSet->GetRowSize());
        row.Id   = 14;
        row.r00  = 1.0;
        row.r01  = 0.0;
        row.r02  = 0.0;
        row.r10  = 0.0;
        row.r11  = 1.0;
        row.r12  = 0.0;
        row.r20  = 0.0;
        row.r21  = 0.0;
        row.r22  = 1.0;
        row.t0   = -0.99010;
        row.t1   = 3.75831;
        row.t2   = 0.03300;
    memcpy(&row.comment,"Station=4(Disk=3),Pent=2(Quad=D,x<0,y>0) geo(-0.375,+3.516) + align(-1.139,+1.410)\x00",1);
    tableSet->AddAt(&row);

    memset(&row,0,tableSet->GetRowSize());
        row.Id   = 15;
        row.r00  = 1.0;
        row.r01  = 0.0;
        row.r02  = 0.0;
        row.r10  = 0.0;
        row.r11  = 1.0;
        row.r12  = 0.0;
        row.r20  = 0.0;
        row.r21  = 0.0;
        row.r22  = 1.0;
        row.t0   = -5.35510;
        row.t1   = 0.28431;
        row.t2   = -0.11100;
    memcpy(&row.comment,"Station=4(Disk=3),Pent=3(Quad=C,x<0,y<0) geo(-4.391,+2.381) + align(-0.964,-1.739)\x00",1);
    tableSet->AddAt(&row);

    memset(&row,0,tableSet->GetRowSize());
        row.Id   = 16;
        row.r00  = 1.0;
        row.r01  = 0.0;
        row.r02  = 0.0;
        row.r10  = 0.0;
        row.r11  = 1.0;
        row.r12  = 0.0;
        row.r20  = 0.0;
        row.r21  = 0.0;
        row.r22  = 1.0;
        row.t0   = 5.57766;
        row.t1   = 0.68105;
        row.t2   = -0.01300;
    memcpy(&row.comment,"Station=4(Disk=3),Pent=4(Quad=B,x>0,y<0) geo(+4.849,+2.481) + align(+1.361,-1.476)\x00",1);
    tableSet->AddAt(&row);

return (TDataSet *)tableSet;
}
