// plotStgcTableShift.C -- the sTGC offsets that the DB tables actually apply, drawn as a
// vector at each quadrant's footprint centre. Unlike plotStgcRadial.C, which fits a
// measured residual, these come straight from the tables:
//
//     shift = (AGML placeholder + stgcOnTpc + stationOnStgc + pentOnStation) - reference
//
// Panels 1 and 2 use Run 22 iteration 0 -- the bare AGML placeholder, before any of our
// tables -- as the common reference, so the two runs are on one baseline. A large part of
// what they show is therefore NOT misalignment: it is the constant difference between
// StFttDb's origin convention and the AGML placeholder, present in both runs. The
// physically interesting quantity is the DIFFERENCE between the two, which is panel 3.
//
// Numbers generated by script/stgcTotalOffsets.py; see FstFttFlipTest/index.html section 11.
// CINT: fixed C arrays, unique loop variable names (see CLAUDE.md).
double s22X[4][4]={
    {+2.1108,+0.8464,+1.7683,+1.7572},
    {+5.9286,+6.0627,+6.0531,+5.5900},
    {-4.9097,-4.9802,-5.8499,-5.3427},
    {-1.1186,-1.1647,-1.0998,-0.9777}};
double s22Y[4][4]={
    {+5.4798,+4.4074,+5.4773,+5.4114},
    {+1.4004,+1.3482,+1.4988,+1.5555},
    {+1.0286,+1.0672,+1.2683,+1.1587},
    {+5.4267,+4.8628,+5.0096,+4.6327}};
double s24X[4][4]={
    {+1.9603,+1.9038,+1.7435,+1.5963},
    {+5.8702,+6.0627,+6.1527,+5.5900},
    {-6.2828,-5.9023,-5.8499,-5.3427},
    {-1.9790,-1.9623,-1.9263,-1.8937}};
double s24Y[4][4]={
    {+6.6301,+6.4842,+7.0376,+6.7203},
    {+1.8498,+1.3482,+2.0230,+2.1773},
    {+1.3415,+1.3703,+1.6391,+1.5476},
    {+5.4267,+6.4340,+6.6370,+6.5802}};
double movX[4][4]={
    {-0.1505,+1.0574,-0.0248,-0.1609},
    {-0.0585,+0.0000,+0.0997,+0.0000},
    {-1.3731,-0.9220,+0.0000,+0.0000},
    {-0.8603,-0.7975,-0.8264,-0.9160}};
double movY[4][4]={
    {+1.1503,+2.0767,+1.5603,+1.3089},
    {+0.4494,+0.0000,+0.5242,+0.6218},
    {+0.3129,+0.3031,+0.3708,+0.3888},
    {+0.0000,+1.5712,+1.6274,+1.9475}};
void drawOne(double vx[4][4], double vy[4][4], const char* title, const char* out,
             double scale, const char* note){
  gStyle->SetOptStat(0);
  // quadrant footprint centres, identical construction to plotStgcRadial.C:
  // 275 mm out along the quadrant's own signs, plus the StFttDb origin offset.
  double sfX[4][4]={{8.09,8.34,6.62,7.54},{112.74,112.14,113.30,113.49},
                    {-107.51,-108.22,-109.87,-108.91},{-3.69,-4.96,-4.36,-3.75}};
  double sfY[4][4]={{95.34,94.33,96.03,95.01},{84.24,83.37,83.61,83.81},
                    {83.60,83.42,84.37,82.81},{95.70,94.40,95.55,94.16}};
  double sx[4]={1,1,-1,-1}, sy[4]={1,-1,-1,1};
  const char* qn[4]={"A","B","C","D"};
  int col[4]={kRed+1,kOrange+7,kAzure+1,kBlue+2};   // same colours as plotStgcRadial.C

  TCanvas* cts=new TCanvas(Form("c_%s",title),"cts",640,640);
  gPad->SetGridx(); gPad->SetGridy();
  TH2F* fr=new TH2F(Form("fr_%s",title),Form("%s;x [cm];y [cm]",title),1,-70,70,1,-60,75);
  fr->Draw();
  TLatex tt; tt.SetTextSize(0.026);
  tt.DrawLatex(-68,69,note);
  TEllipse* bp=new TEllipse(0,0,4.1,4.1); bp->SetFillStyle(0); bp->SetLineStyle(2); bp->Draw();
  tt.SetTextSize(0.022); tt.DrawLatex(5,-2,"beampipe");

  for(int iq=0;iq<4;iq++){
    for(int is=0;is<4;is++){
      double cx=(275.0*sx[iq]+sfX[iq][is])/10.0;
      double cy=(275.0*sy[iq]+sfY[iq][is])/10.0;
      cx += (is-1.5)*4.0;                       // fan the four stations so they do not overlap
      TMarker* mk=new TMarker(cx,cy,20); mk->SetMarkerColor(col[iq]); mk->SetMarkerSize(0.8); mk->Draw();
      TArrow* a=new TArrow(cx,cy,cx+scale*vx[iq][is],cy+scale*vy[iq][is],0.012,"|>");
      a->SetLineColor(col[iq]); a->SetFillColor(col[iq]); a->SetLineWidth(2); a->Draw();
    }
    TLatex q; q.SetTextSize(0.034); q.SetTextColor(col[iq]);
    q.DrawLatex(sx[iq]*58.0-2.0, sy[iq]*(sy[iq]>0?64.0:52.0), qn[iq]);
  }
  cts->SaveAs(out);
}

void plotStgcTableShift(){
  drawOne(s22X,s22Y,"Run 22 final offsets vs AGML nominal",
          "FstFttFlipTest/plots/shift_run22.png", 4.0,
          "arrows #times4; includes the StFttDb-origin term, common to both runs");
  drawOne(s24X,s24Y,"Run 24 final offsets vs AGML nominal",
          "FstFttFlipTest/plots/shift_run24.png", 4.0,
          "arrows #times4; same reference and scale as the Run 22 panel");
  drawOne(movX,movY,"Run 24 #minus Run 22: the movement between the runs",
          "FstFttFlipTest/plots/shift_movement.png", 12.0,
          "arrows #times12; convention term cancels, so this is the movement");
}
