#!/usr/bin/env python3
"""Add per-quadrant deltas to an existing pentOnStation table, producing the next
timestamped entry.

This is the correct update from iteration 2 on. The absolute form in
script/stgcQuadOffsets.C is valid only while StFttDb is in hardcoded mode; once DB
mode is on, hits already sit at (AGML placeholder + previous table), so a new table
is  previous + delta, with delta = -(measured residual).

The deltas come from `stgcQuadOffsets.C(file, 0, 2)`, which prints lines of the form
    >>> DELTA <disk> <quad> <d_t0> <d_t1>

Usage:
    stgcTableAddDelta.py PREV.C DELTAS.txt OUT.C

Rows are station-major with pentagon order A,D,C,B within a station, which is the
order the .C file already writes them in and what AGML's <Misalign row="N"/> indexes.
"""
import re
import sys

PENT_ORDER = ["A", "D", "C", "B"]          # pentagon k within a station


def read_deltas(path):
    """{(disk, quad): (dt0, dt1)} from the DELTA lines; incomplete cells are skipped."""
    out = {}
    pat = re.compile(r">>>\s*DELTA\s+(\d)\s+([ABCD])\s+([-+0-9.]+)\s+([-+0-9.]+)")
    for line in open(path):
        m = pat.search(line)
        if m:
            out[(int(m.group(1)), m.group(2))] = (float(m.group(3)), float(m.group(4)))
    return out


def main():
    if len(sys.argv) != 4:
        sys.exit(__doc__)
    prev, deltafile, out = sys.argv[1:]
    deltas = read_deltas(deltafile)
    if not deltas:
        sys.exit("no DELTA lines found in %s" % deltafile)

    src = open(prev).read()
    # row order in the file: station-major, pentagon A,D,C,B
    order = [(st, PENT_ORDER[k]) for st in range(4) for k in range(4)]
    # t0 and t1 are interleaved per row, so walk them together rather than separately
    rows = re.findall(r"        row\.t0   = ([-+0-9.eE]+);\n        row\.t1   = ([-+0-9.eE]+);", src)
    if len(rows) != 16:
        sys.exit("expected 16 rows in %s, found %d" % (prev, len(rows)))

    it = iter(range(16))

    def sub_pair(m):
        i = next(it)
        st, q = order[i]
        d0, d1 = deltas.get((st, q), (0.0, 0.0))
        return ("        row.t0   = %.5f;\n        row.t1   = %.5f;"
                % (float(m.group(1)) + d0, float(m.group(2)) + d1))

    new, n = re.subn(
        r"        row\.t0   = ([-+0-9.eE]+);\n        row\.t1   = ([-+0-9.eE]+);",
        sub_pair, src)
    assert n == 16, n

    hdr = ("// Generated by script/stgcTableAddDelta.py:  %s + deltas from %s\n"
           "// new = previous + delta, delta = -(measured residual). Absolute\n"
           "// regeneration is WRONG once StFttDb runs in DB mode -- see the guard in\n"
           "// script/stgcQuadOffsets.C.\n" % (prev, deltafile))
    open(out, "w").write(hdr + new)
    print("wrote %s  (%d rows updated, %d cells had deltas)" % (out, n, len(deltas)))


if __name__ == "__main__":
    main()
